/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTestsRouteImport } from './routes/admin.tests'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as TestCourseIdRouteImport } from './routes/test.$courseId'
import { Route as LearnCourseIdLessonIdRouteImport } from './routes/learn.$courseId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestsRoute = AdminTestsRouteImport.update({
  id: '/admin/tests',
  path: '/admin/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCourseIdRoute = TestCourseIdRouteImport.update({
  id: '/test/$courseId',
  path: '/test/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdLessonIdRoute = LearnCourseIdLessonIdRouteImport.update({
  id: '/learn/$courseId/$lessonId',
  path: '/learn/$courseId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tests': typeof AdminTestsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/test/$courseId': typeof TestCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/learn/$courseId/$lessonId': typeof LearnCourseIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tests': typeof AdminTestsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/test/$courseId': typeof TestCourseIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/learn/$courseId/$lessonId': typeof LearnCourseIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tests': typeof AdminTestsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/test/$courseId': typeof TestCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/learn/$courseId/$lessonId': typeof LearnCourseIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/certificates'
    | '/dashboard'
    | '/results'
    | '/admin/courses'
    | '/admin/students'
    | '/admin/tests'
    | '/courses/$courseId'
    | '/test/$courseId'
    | '/admin/'
    | '/courses/'
    | '/learn/$courseId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/certificates'
    | '/dashboard'
    | '/results'
    | '/admin/courses'
    | '/admin/students'
    | '/admin/tests'
    | '/courses/$courseId'
    | '/test/$courseId'
    | '/admin'
    | '/courses'
    | '/learn/$courseId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/certificates'
    | '/dashboard'
    | '/results'
    | '/admin/courses'
    | '/admin/students'
    | '/admin/tests'
    | '/courses/$courseId'
    | '/test/$courseId'
    | '/admin/'
    | '/courses/'
    | '/learn/$courseId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CertificatesRoute: typeof CertificatesRoute
  DashboardRoute: typeof DashboardRoute
  ResultsRoute: typeof ResultsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTestsRoute: typeof AdminTestsRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  TestCourseIdRoute: typeof TestCourseIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LearnCourseIdLessonIdRoute: typeof LearnCourseIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tests': {
      id: '/admin/tests'
      path: '/admin/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$courseId': {
      id: '/test/$courseId'
      path: '/test/$courseId'
      fullPath: '/test/$courseId'
      preLoaderRoute: typeof TestCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId/$lessonId': {
      id: '/learn/$courseId/$lessonId'
      path: '/learn/$courseId/$lessonId'
      fullPath: '/learn/$courseId/$lessonId'
      preLoaderRoute: typeof LearnCourseIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CertificatesRoute: CertificatesRoute,
  DashboardRoute: DashboardRoute,
  ResultsRoute: ResultsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTestsRoute: AdminTestsRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  TestCourseIdRoute: TestCourseIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LearnCourseIdLessonIdRoute: LearnCourseIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
